### PR TITLE
Fix link re exception

### PR DESCRIPTION
**Pull request by wolfsilver**
if use `/link hi(` to filter. etm will throw `re.error` exception.

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/efb_telegram_master/__init__.py", line 443, in error
    raise error
  File "/usr/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/lib/python3.7/site-packages/telegram/ext/handler.py", line 117, in handle_update
    return self.callback(update, context)
  File "/usr/lib/python3.7/site-packages/efb_telegram_master/chat_binding.py", line 188, in link_chat_show_list
    return self.link_chat_gen_list(message.from_user.id, pattern=" ".join(args))
  File "/usr/lib/python3.7/site-packages/efb_telegram_master/chat_binding.py", line 334, in link_chat_gen_list
    source_chats=chats)
  File "/usr/lib/python3.7/site-packages/efb_telegram_master/chat_binding.py", line 225, in slave_chats_pagination
    re_filter = re.compile(pattern, re.DOTALL | re.IGNORECASE) if pattern else None
  File "/usr/lib/python3.7/re.py", line 234, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.7/sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.7/sre_parse.py", line 819, in _parse
    source.tell() - start)
re.error: missing ), unterminated subpattern at position 2
```

### CODE REVIEW

**Comment by blueset** [comment]
Nice catch! Indeed I didn‘t realize the error when the regular expression supplied is invalid.

But I think it could be better to give an error message, or treat the query as plain string, rather than dropping the query string completely.

Let me know if you have any different opinion.

**Comment by wolfsilver** [comment]
It's better to treat the query as plain string.

**Comment by wolfsilver** [comment]
I tried to use `re.escape` to escape compiling. But not work...

**Comment by blueset** [comment]
What‘s your code and the error message you got with `re.escape`?

**Comment by wolfsilver** [comment]
No error occured. But ETM returns noting.

```
try:
    re_filter = re.compile(pattern, re.DOTALL | re.IGNORECASE) if pattern else None
except re.error:
    re_filter = re.compile(re.escape(pattern), re.DOTALL | re.IGNORECASE) if pattern else None
```

image

**Comment by blueset** [comment]
I don‘t currently have a chat that has any regex pattern chars, so I can‘t check it in the real environment for now. I‘ll take a look at this issue later when my mock slave channel for unit test is ready. I just had a simple test with the `re` module and seems that it should work.

```python
>>> import re
>>> pattern = re.escape('hi(')
>>> filter = re.compile(pattern, re.DOTALL | re.IGNORECASE)
>>> filter.search("lorem ipsum hi(this is a test)")
<re.Match object; span=(12, 15), match='hi('>
>>>
```

Don‘t hesitate to raise up any question or issue you have found in the code along the way.

**Comment by wolfsilver** [comment]
My bad. I used a wrong nick to query.
It's OK now.

**Pull request merged**
